PlayededLocalizationTable = {
    NEW_TIME_PLAYED_MSG = {
        default = "New gametime recorded for this character.",
        frFR = "Nouveau temps de jeu enregistré pour ce personnage.",
        deDE = "Neue Spielzeit für diesen Charakter aufgezeichnet.",
        esES = "Nuevo tiempo de juego registrado para este personaje.",
        esMX = "Nuevo tiempo de juego registrado para este personaje.",
        ptBR = "Novo tempo de jogo registrado para este personagem.",
        ruRU = "Новое время игры записано для этого персонажа.",
        zhCN = "为这个角色记录的新游戏时间。",
        zhTW = "為這個角色記錄的新遊戲時間。",
        koKR = "이 캐릭터에 대해 새 게임 시간을 기록했습니다.",
        ukUA = "Записано новий час гри для цього персонажа."
    },
    ACCEPTED_COMMANDS_MSG = {
        default = "Allowed commands for Playeded :",
        frFR = "Commandes acceptées pour Playeded :",
        deDE = "Erlaubte Befehle für Playeded:",
        esES = "Comandos permitidos para Playeded:",
        esMX = "Comandos permitidos para Playeded:",
        ptBR = "Comandos permitidos para Playeded:",
        ruRU = "Разрешенные команды для Playeded:",
        zhCN = "Playeded 的允许命令：",
        zhTW = "Playeded 的允許命令：",
        koKR = "Playeded에 대한 허용된 명령어:",
        ukUA = "Дозволені команди для Playeded:"
    },
    INFO_ALL_COMMAND_MSG = {
        default = "Display overall gametime.",
        frFR = "Affiche le temps de jeu total.",
        deDE = "Gesamtspielzeit anzeigen.",
        esES = "Mostrar el tiempo de juego total.",
        esMX = "Mostrar el tiempo de juego total.",
        ptBR = "Exibir o tempo de jogo total.",
        ruRU = "Отобразить общее время игры.",
        zhCN = "显示总游戏时间。",
        zhTW = "顯示總遊戲時間。",
        koKR = "총 게임 시간을 표시합니다.",
        ukUA = "Показати загальний час гри."
    },
    INFO_SERVER_COMMAND_MSG = {
        default = "Display gametime on this server.",
        frFR = "Affiche le temps de jeu sur ce serveur.",
        deDE = "Spielzeit auf diesem Server anzeigen.",
        esES = "Mostrar el tiempo de juego en este servidor.",
        esMX = "Mostrar el tiempo de juego en este servidor.",
        ptBR = "Exibir o tempo de jogo neste servidor.",
        ruRU = "Показать время игры на этом сервере.",
        zhCN = "显示此服务器上的游戏时间。",
        zhTW = "顯示此伺服器上的遊戲時間。",
        koKR = "이 서버의 게임 시간을 표시합니다.",
        ukUA = "Показати час гри на цьому сервері."
    },
    INFO_RESETALL_COMMAND_MSG = {
        default = "Reset saved overall gametime.",
        frFR = "Réinitialise le temps de jeu total enregistré.",
        deDE = "Gespeicherte Gesamtspielzeit zurücksetzen.",
        esES = "Restablecer el tiempo de juego total guardado.",
        esMX = "Restablecer el tiempo de juego total guardado.",
        ptBR = "Redefinir o tempo de jogo total salvo.",
        ruRU = "Сбросить сохраненное общее время игры.",
        zhCN = "重置保存的总游戏时间。",
        zhTW = "重置保存的總遊戲時間。",
        koKR = "저장된 총 게임 시간을 초기화합니다.",
        ukUA = "Скинути збережений загальний час гри."
    },
    RESETALL_CONFIRMATION_MSG = {
        default = "Overall gametime have been reset.",
        frFR = "Tous les temps de jeux ont été réinitialisés.",
        deDE = "Die gesamte Spielzeit wurde zurückgesetzt.",
        esES = "Se ha restablecido todo el tiempo de juego.",
        esMX = "Se ha restablecido todo el tiempo de juego.",
        ptBR = "Todo o tempo de jogo foi redefinido.",
        ruRU = "Общее время игры было сброшено.",
        zhCN = "所有游戏时间已重置。",
        zhTW = "所有遊戲時間已重置。",
        koKR = "모든 게임 시간이 초기화되었습니다.",
        ukUA = "Загальний час гри було скинуто."
    },
    OVERALL_PLAYEDTIME_DISPLAY_MSG = {
        default = "You played %s on this account.",
        frFR = "Vous avez joué %s sur ce compte.",
        deDE = "Sie haben %s auf diesem Konto gespielt.",
        esES = "Has jugado %s en esta cuenta.",
        esMX = "Has jugado %s en esta cuenta.",
        ptBR = "Você jogou %s nesta conta.",
        ruRU = "Вы играли %s на этой учетной записи.",
        zhCN = "您在此帐户上玩了 %s。",
        zhTW = "您在此帳戶上玩了 %s。",
        koKR = "이 계정에서 %s를 플레이했습니다.",
        ukUA = "Ви грали %s на цьому обліковому записі."
    },
    SERVER_PLAYEDTIME_DISPLAY_MSG = {
        default = "You played %s on %s.",
        frFR = "Vous avez joué %s sur le serveur %s.",
        deDE = "Sie haben %s auf dem Server %s gespielt.",
        esES = "Has jugado %s en el servidor %s.",
        esMX = "Has jugado %s en el servidor %s.",
        ptBR = "Você jogou %s no servidor %s.",
        ruRU = "Вы играли %s на сервере %s.",
        zhCN = "您在服务器 %s 上玩了 %s。",
        zhTW = "您在伺服器 %s 上玩了 %s。",
        koKR = "%s 서버에서 %s를 플레이했습니다.",
        ukUA = "Ви грали %s на сервері %s."
    },
    DAY = {
        default = "day",
        frFR = "jour",
        deDE = "Tag",
        esES = "día",
        esMX = "día",
        ptBR = "dia",
        ruRU = "день",
        zhCN = "天",
        zhTW = "天",
        koKR = "일",
        ukUA = "день"
    },
    DAYS = {
        default = "days",
        frFR = "jours",
        deDE = "Tage",
        esES = "días",
        esMX = "días",
        ptBR = "dias",
        ruRU = "дней",
        zhCN = "天",
        zhTW = "天",
        koKR = "일",
        ukUA = "дні"
    },
    HOUR = {
        default = "hour",
        frFR = "heure",
        deDE = "Stunde",
        esES = "hora",
        esMX = "hora",
        ptBR = "hora",
        ruRU = "час",
        zhCN = "小时",
        zhTW = "小時",
        koKR = "시간",
        ukUA = "година"
    },
    HOURS = {
        default = "hours",
        frFR = "heures",
        deDE = "Stunden",
        esES = "horas",
        esMX = "horas",
        ptBR = "horas",
        ruRU = "часов",
        zhCN = "小时",
        zhTW = "小時",
        koKR = "시간",
        ukUA = "годин"
    },
    MINUTE = {
        default = "minute",
        frFR = "minute",
        deDE = "Minute",
        esES = "minuto",
        esMX = "minuto",
        ptBR = "minuto",
        ruRU = "минута",
        zhCN = "分钟",
        zhTW = "分鐘",
        koKR = "분",
        ukUA = "хвилина"
    },
    MINUTES = {
        default = "minutes",
        frFR = "minutes",
        deDE = "Minuten",
        esES = "minutos",
        esMX = "minutos",
        ptBR = "minutos",
        ruRU = "минут",
        zhCN = "分钟",
        zhTW = "分鐘",
        koKR = "분",
        ukUA = "хвилин"
    },
    SECOND = {
        default = "second",
        frFR = "seconde",
        deDE = "Sekunde",
        esES = "segundo",
        esMX = "segundo",
        ptBR = "segundo",
        ruRU = "секунда",
        zhCN = "秒",
        zhTW = "秒",
        koKR = "초",
        ukUA = "секунда"
    },
    SECONDS = {
        default = "seconds",
        frFR = "secondes",
        deDE = "Sekunden",
        esES = "segundos",
        esMX = "segundos",
        ptBR = "segundos",
        ruRU = "секунд",
        zhCN = "秒",
        zhTW = "秒",
        koKR = "초",
        ukUA = "секунд"
    }
}


function GetPlayededLocalizedText(key)
    return PlayededLocalizationTable[key][locale] or PlayededLocalizationTable[key]["default"] or key
end